sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
    - $HOME/.m2
env:
  global:
    # ARTIFACTORY_USERNAME
    - secure: "oxZe+DVpeVs30ztBLC7i1e2TMLLXkioN/jGhFFvDCYTc2Wlvek2CjEciUxzU8kDHQW5Op5ac95EuhuxCKZ8sAk71V5BcMoeUuPHMBAy50RNI9p5v7PQV82rFyhrfHbFQVaIXyPa9ryXdbPVkIQR/QWGBKrd6UgTW8/Yl5tWPer8="
    # ARTIFACTORY_PASSWORD
    - secure: "aojROPLndGO4ERdTh7L6D4G3WLAPlIxe2LIxnT8HWIwYtFbMKICKiRq0Dd9gjT/slUbJhtcO7dAuprCVFpAcblJQEMGPthdxAQbYvoI+U7SyoWQ/beceaV2BdiKJgEQaNHY79JGq9gMIg7rM4GdHfdZMHNWQyrGDOs0LKZKKqWg="
    # AWS_ACCESS_KEY_ID
    - secure: "EArASj44Fg0JYQW0lSh/tYdOYvyYKJu/wSiTmir/Dj3vBjzNo/dzkuHxPD6bUiLPLnYWgp9E60wYC+1YuBzcv/SjPLrcdfjxRlrQdcnK2LyRV7eLNt6cRJiL9B5YKoae+W/83jGx7qooF/2EzPBbWv5tfnOGukQ8UaZ0KwDSzfA="
    # AWS_SECRET_ACCESS_KEY
    - secure: "YEzSt/5cVG92lm6Tk5nBxJJDUSYRieM5wXV9eoQtkXuf5kDmF0x78+9QFlbKCG/Mda/PNnjWjoCVZag/OL4UBib14dnsLwE3hVEzKMYDTWC8ttgtk3FRtstKmLlqPX9TV5sO1j3niZUTGMcbS2CBsjHnWPlEF+9uGoAL7m+IshM="
addons:
  sonarcloud:
    organization: "opetushallitus"
    token:
      secure: "SGrBqpGlzOEnNM0Ro4UIVobFONGD2UP1ckGUmgbXTBvF1yhzW0OAsc7d0W7OEQ8YCfX4vScovSqHZCD6dXQc5tu11cN0bNhsNlnBzfas78AeIi8jL0Tg6sVs449vpv8M2RfCCjGFkcWG2aiA+epGuFjFc97UhoLg64HF/ieWe8g="
before_install:
  - nvm install 12.18.1
  - nvm use 12.18.1
install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="koodisto"

script:
  - mvn -version
  - mvn clean install sonar:sonar -Dsonar.projectKey=Opetushallitus_koodisto -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}
  - mv koodisto-service/target/koodisto-service.war $DOCKER_BUILD_DIR/artifact/koodisto-service.war
  - mv koodisto-ui/target/koodisto-ui.war $DOCKER_BUILD_DIR/artifact/koodisto-ui.war
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-war-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-war.sh $ARTIFACT_NAME

deploy:
  - provider: script
    script: mvn deploy -pl fi.vm.sade.koodisto:koodisto,koodisto-api -am -DskipTests --settings ci-tools/common/maven-settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
    on:
      all_branches: true
