<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="downloadService"
    targetNamespace="http://service.koodisto.sade.vm.fi/" xmlns:ns1="http://service.koodisto.sade.vm.fi/types"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://service.koodisto.sade.vm.fi/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xsd:schema targetNamespace="http://service.koodisto.sade.vm.fi/">
            <xsd:import namespace="http://service.koodisto.sade.vm.fi/types"
                schemaLocation="downloadService.xsd" />
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="downloadResponse">
        <wsdl:part element="ns1:downloadResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="download">
        <wsdl:part element="ns1:download" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="genericFault">
        <wsdl:part name="fault" element="ns1:genericFaultInfo"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="downloadService">
        <wsdl:documentation>Palvelurajapinta koodien lataamiseen eri
            formaateissa.
        </wsdl:documentation>
        <wsdl:operation name="download">
            <wsdl:documentation>Lataa koodiston koodit parametrina
                annetussa formaatissa.
            </wsdl:documentation>
            <wsdl:input message="tns:download" name="download">
            </wsdl:input>
            <wsdl:output message="tns:downloadResponse"
                name="downloadResponse">
            </wsdl:output>
            <wsdl:fault name="fault" message="tns:genericFault"></wsdl:fault>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="downloadServiceSoapBinding" type="tns:downloadService">
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="download">
            <soap:operation soapAction="" style="document" />
            <wsdl:input name="download">
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output name="downloadResponse">
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="downloadService">
        <wsdl:port binding="tns:downloadServiceSoapBinding"
            name="downloadServicePort">
            <soap:address location="http://localhost:8181/cxf/downloadService" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>