<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="uploadService"
    targetNamespace="http://service.koodisto.sade.vm.fi/" xmlns:ns1="http://service.koodisto.sade.vm.fi/types"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://service.koodisto.sade.vm.fi/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xsd:schema targetNamespace="http://service.koodisto.sade.vm.fi/">
            <xsd:import namespace="http://service.koodisto.sade.vm.fi/types"
                schemaLocation="uploadService.xsd" />
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="upload">
        <wsdl:part element="ns1:upload" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="uploadResponse">
        <wsdl:part element="ns1:uploadResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="genericFault">
        <wsdl:part name="fault" element="ns1:genericFaultInfo"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="uploadService">
        <wsdl:documentation>Palvelurajapinta koodien lähettämiseen palvelimell eri muodoissa</wsdl:documentation>
        <wsdl:operation name="upload">
            <wsdl:documentation>Lähettää koodit annetussa formaatissa ja lisää ne annettuun koodistoon</wsdl:documentation>
            <wsdl:input message="tns:upload" name="upload">
            </wsdl:input>
            <wsdl:output message="tns:uploadResponse" name="uploadResponse">
            </wsdl:output>
            <wsdl:fault name="fault" message="tns:genericFault"></wsdl:fault>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="uploadServiceSoapBinding" type="tns:uploadService">
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="upload">
            <soap:operation soapAction="" style="document" />
            <wsdl:input name="upload">
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output name="uploadResponse">
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="uploadService">
        <wsdl:port binding="tns:uploadServiceSoapBinding"
            name="uploadServicePort">
            <soap:address location="http://localhost:8181/cxf/uploadService" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>