version: '3'
services:
  database:
    container_name: oph-postgres-db
    build: .
    environment:
      - POSTGRES_DB=koodisto
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./backup:/tmp/backup
      - ./database-data:/var/lib/postgresql/data/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  database-data:
