version: '3'
services:
  database:
    container_name: oph-postgres-db
    build: .
    environment:
      - POSTGRES_DB=koodisto
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: always
volumes:
  database-data:
