name: koodisto-service
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'koodisto-ui/**'
      - 'koodisto-ui-server/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'koodisto-ui/**'
      - 'koodisto-ui-server/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Maven version
        run: mvn --version
      - name: Build
        run: mvn clean install
      - name: Upload koodisto-service-war
        uses: actions/upload-artifact@v2
        with:
          name: koodisto-service-war
          path: koodisto-service/target/koodisto-service.war
  deploy-container:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download koodisto-ui-server-jar
        uses: actions/download-artifact@v2
        with:
          name: koodisto-service-war
      - name: Build Docker Conainer
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          export BASE_IMAGE="baseimage-war-openjdk11:master"
          export ARTIFACT_NAME="koodisto"
          cp koodisto-service.war $DOCKER_BUILD_DIR/artifact/koodisto-service.war
          cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/
          ./ci-tools/common/pull-image.sh
          ./ci-tools/github-build/build-fatjar.sh $ARTIFACT_NAME
          ./ci-tools/github-build/upload-image.sh $ARTIFACT_NAME
